name: Lint Code and Unit Tests 

on:
  - push
  - pull_request

jobs:
  build:
    name: Lint Code and Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install black and tox
      run: |
        pip install tox
        pip install black==20.8b1

    - name: Check Black formatting
      run: black --check .

    - name: Unit Tests and Linting
      run:
        tox -e lint
        tox -e unit
